# Automatically generated by ./configure
# Command line: --allow-fetch
CONFIGURE_STATUS := started
CONFIGURE_ERROR := 
CONFIGURE_COMMAND_LINE := --fetch re2 --fetch gtest --fetch v8 --fetch jemalloc --allow-fetch
CONFIGURE_MAGIC_NUMBER := 2
# Bash
FETCH_LIST := 
FETCH_VERSIONS := 
LIB_SEARCH_PATHS := 
# Use ccache
USE_CCACHE := 0
# C++ Compiler
COMPILER := GCC
CXX := /usr/bin/c++
# Host System
MACHINE := x86_64-linux-gnu
# Build System
# Cross-compiling
CROSS_COMPILING := 0
# Host Operating System
OS := Linux
PTHREAD_LIBS := -pthread
RT_LIBS := -lrt
M_LIBS := -lm
# Build Architecture
GCC_ARCH := x86_64
GCC_ARCH_REDUCED := x86_64
# C++11
CXX11_LIBS += 
HAS_CXX11 := 1
# Precompiled web assets
USE_PRECOMPILED_WEB_ASSETS := 1
# Protobuf compiler
PROTOC := /usr/bin/protoc
PROTOC_BIN_DEP := 
# python
PYTHON := /usr/bin/python
PYTHON_BIN_DEP := 
# Node.js package manager
FETCH_LIST += node
node_VERSION := 0.12.2
node_DEPENDS := 
NPM = $(abspath $(SUPPORT_BUILD_DIR)/node_0.12.2/bin/npm)
NPM_BIN_DEP = $(SUPPORT_BUILD_DIR)/node_0.12.2/bin/npm
# coffee
FETCH_LIST += coffee-script
coffee-script_VERSION := 1.10.0
coffee-script_DEPENDS := node
COFFEE = $(abspath $(SUPPORT_BUILD_DIR)/coffee-script_1.10.0/bin/coffee)
COFFEE_BIN_DEP = $(SUPPORT_BUILD_DIR)/coffee-script_1.10.0/bin/coffee
# Browserify
FETCH_LIST += browserify
browserify_VERSION := 12.0.1
browserify_DEPENDS := node
BROWSERIFY = $(abspath $(SUPPORT_BUILD_DIR)/browserify_12.0.1/bin/browserify)
BROWSERIFY_BIN_DEP = $(SUPPORT_BUILD_DIR)/browserify_12.0.1/bin/browserify
# bluebird
FETCH_LIST += bluebird
bluebird_VERSION := 2.9.32
bluebird_DEPENDS := node
BLUEBIRD = $(abspath $(SUPPORT_BUILD_DIR)/bluebird_2.9.32/bin/bluebird)
BLUEBIRD_BIN_DEP = $(SUPPORT_BUILD_DIR)/bluebird_2.9.32/bin/bluebird
# web UI dependencies
FETCH_LIST += admin-deps
admin-deps_VERSION := 2.0.3
admin-deps_DEPENDS := node
GULP = $(abspath $(SUPPORT_BUILD_DIR)/admin-deps_2.0.3/bin/gulp)
GULP_BIN_DEP = $(SUPPORT_BUILD_DIR)/admin-deps_2.0.3/bin/gulp
# wget
WGET := /usr/bin/wget
WGET_BIN_DEP := 
# curl
# Google Test
FETCH_LIST += gtest
gtest_VERSION := 1.7.0
gtest_DEPENDS := 
gtest_LIB_NAME += GTEST
HAS_GTEST := 1
GTEST_LIBS_DEP = $(SUPPORT_BUILD_DIR)/gtest_1.7.0/lib/libgtest.a
GTEST_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/gtest_1.7.0/include
GTEST_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/gtest_1.7.0/include
# termcap
TERMCAP_LIBS += -ltermcap
HAS_TERMCAP := 1
HAS_TERMCAP := 1
TERMCAP_INCLUDE := 
TERMCAP_INCLUDE_DEP := 
TERMCAP_LIBS_DEP := 
# boost_system
BOOST_SYSTEM_LIBS += -lboost_system
HAS_BOOST_SYSTEM := 1
HAS_BOOST_SYSTEM := 1
BOOST_SYSTEM_INCLUDE := 
BOOST_SYSTEM_INCLUDE_DEP := 
BOOST_SYSTEM_LIBS_DEP := 
# protobuf
PROTOBUF_LIBS += -lprotobuf
HAS_PROTOBUF := 1
HAS_PROTOBUF := 1
PROTOBUF_INCLUDE := 
PROTOBUF_INCLUDE_DEP := 
PROTOBUF_LIBS_DEP := 
# v8 javascript engine
FETCH_LIST += v8
v8_VERSION := 3.30.33.16
v8_DEPENDS := 
v8_LIB_NAME += V8
HAS_V8 := 1
V8_LIBS_DEP = $(SUPPORT_BUILD_DIR)/v8_3.30.33.16/lib/libv8.a
V8_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/v8_3.30.33.16/include
V8_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/v8_3.30.33.16/include
# RE2
FETCH_LIST += re2
re2_VERSION := 20140111
re2_DEPENDS := 
re2_LIB_NAME += RE2
HAS_RE2 := 1
RE2_LIBS_DEP = $(SUPPORT_BUILD_DIR)/re2_20140111/lib/libre2.a
RE2_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/re2_20140111/include
RE2_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/re2_20140111/include
# z
Z_LIBS += -lz
HAS_Z := 1
HAS_Z := 1
Z_INCLUDE := 
Z_INCLUDE_DEP := 
Z_LIBS_DEP := 
# crypto
FETCH_LIST += openssl
openssl_VERSION := 1.0.1t
openssl_DEPENDS := 
openssl_LIB_NAME += CRYPTO
HAS_CRYPTO := 1
CRYPTO_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libcrypto.a
CRYPTO_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
CRYPTO_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
# ssl
openssl_LIB_NAME += SSL
HAS_SSL := 1
SSL_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libssl.a
SSL_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
SSL_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
# curl
CURL_LIBS += -lcurl
HAS_CURL := 1
HAS_CURL := 1
CURL_INCLUDE := 
CURL_INCLUDE_DEP := 
CURL_LIBS_DEP := 
V8_PRE_3_19 := 0
# malloc
ALLOCATOR := jemalloc
DEFAULT_ALLOCATOR := jemalloc
# jemalloc
FETCH_LIST += jemalloc
jemalloc_VERSION := 4.1.0
jemalloc_DEPENDS := 
jemalloc_LIB_NAME += JEMALLOC
HAS_JEMALLOC := 1
JEMALLOC_LIBS_DEP = $(SUPPORT_BUILD_DIR)/jemalloc_4.1.0/lib/libjemalloc.a
JEMALLOC_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/jemalloc_4.1.0/include
JEMALLOC_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/jemalloc_4.1.0/include
STATIC_MALLOC := 1
MALLOC_LIBS = $(JEMALLOC_LIBS)
MALLOC_LIBS_DEP = $(JEMALLOC_LIBS_DEP)
# Test protobuf
# Test boost
BOOST_LIBS += 
HAS_BOOST := 1
HAS_BOOST := 1
BOOST_INCLUDE := 
BOOST_INCLUDE_DEP := 
BOOST_LIBS_DEP := 
# Test OpenSSL
openssl_LIB_NAME += OPENSSL
HAS_OPENSSL := 1
OPENSSL_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libopenssl.a
OPENSSL_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
OPENSSL_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
STATIC_V8 := 1
ALLOW_FETCH := 1
# Installation prefix
PREFIX := /usr/local
# Configuration prefix
SYSCONFDIR := /usr/local/etc
# Runtime data prefix
LOCALSTATEDIR := /usr/local/var
CONFIGURE_STATUS := success
